### ISSUE TITLE
pipelineRun attestation not being sent to OCI registry

### ISSUE THREAD

**Issue by mtcolman** [tektoncd/chains#1001]
Hi, not sure if this is a bug or I've done something wrong...

Using Tekton Chains: v0.16.1 (via OpenShift Pipelines 1.11.2).

I have this config in `chains-config` in `openshift-pipelines`
```
apiVersion: v1
kind: ConfigMap
data:
  artifacts.oci.format: simplesigning
  artifacts.oci.storage: oci
  artifacts.pipelinerun.format: slsa/v1
  artifacts.pipelinerun.storage: oci
  transparency.enabled: "false"
metadata:
  name: chains-config
  namespace: openshift-pipelines
```

When I have taskrun.format and taskrun.storage set, I get a taskRun attestation generated and sent to the repo, alongisde the image signature, so I know the credentials I've supplied to the SA and task work. However I cannot get it to work when I use pipelinerun items in the config map. I make sure to: delete the chains-controller pod: `oc delete po -n openshift-pipelines -l app=tekton-chains-controller` and allow it to restart, plus use `oc create -f pipelineRun.yaml` to create a new pipelineRun.

The pipelineRun yaml shows:
```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: kaniko-chains-pipelinerun-
  annotations:
    chains.tekton.dev/signed: 'true'
```

But the `.att` file never appears in my repo (but note the `.sig` does):
![image](https://github.com/tektoncd/chains/assets/33348891/3a7ad27c-87e1-4957-bd7a-55a6cbe18dc0)

My Kaniko task produces `IMAGE_URL` and `IMAGE_DIGEST`.

PipelineRun:
```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: kaniko-chains-pipelinerun-
spec:
  pipelineRef:
    name: simple-kaniko-chains-two-tasks
  podTemplate:
    imagePullSecrets:
    - name: pipeline-registry
  serviceAccountName: pipeline
  workspaces:
  - emptyDir: {}
    name: source
  - name: dockerconfig
    secret:
      secretName: chains-test
```

Pipeline:
```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: simple-kaniko-chains-two-tasks
spec:
  workspaces:
  - name: source
  - name: dockerconfig
  tasks:
    - name: kaniko-starter
      taskRef:
        name: kaniko-starter
    - name: kaniko-chains
      taskRef:
        name: kaniko-chains
      runAfter:
        - kaniko-starter
      workspaces:
      - name: source
        workspace: source
      - name: dockerconfig
        workspace: dockerconfig
```

Task "kaniko-starter" (literally just a dummy to give an additional task):
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kaniko-starter
spec:
  steps:
  - name: pretend
    image: bash
    script: |
      set -e
      echo "hello there"
```

Task "kaniko-chains" (taken from the tutorial - amended to use my registry and newer kaniko image):
```
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kaniko-chains
spec:
  description: >-
    This Task builds a simple Dockerfile with kaniko and pushes to a registry.
    This Task stores the image name and digest as results, allowing Tekton Chains to pick up
    that an image was built & sign it.
  params:
  - name: IMAGE
    description: Name (reference) of the image to build.
    default: "<redacted>/kaniko-chains"
  - name: DOCKERFILE
    description: Path to the Dockerfile to build.
    default: ./Dockerfile
  - name: CONTEXT
    description: The build context used by Kaniko.
    default: ./
  - name: EXTRA_ARGS
    default: ""
  - name: BUILDER_IMAGE
    description: The image on which builds will run (default is v1.17.0)
    default: gcr.io/kaniko-project/executor:v1.17.0 # gcr.io/kaniko-project/executor:v1.5.1@sha256:c6166717f7fe0b7da44908c986137ecfeab21f31ec3992f6e128fff8a94be8a5
  workspaces:
  - name: source
    description: Holds the context and Dockerfile
  - name: dockerconfig
    description: Includes a docker `config.json`
    optional: true
    mountPath: /kaniko/.docker
  results:
  - name: IMAGE_DIGEST
    description: Digest of the image just built.
  - name: IMAGE_URL
    description: URL of the image just built.
  steps:
  - name: add-dockerfile
    workingDir: $(workspaces.source.path)
    image: bash
    script: |
      set -e
      echo "FROM alpine@sha256:69e70a79f2d41ab5d637de98c1e0b055206ba40a8145e7bddb55ccc04e13cf8f" | tee $(params.DOCKERFILE)
  - name: build-and-push
    workingDir: $(workspaces.source.path)
    image: $(params.BUILDER_IMAGE)
    args:
    - $(params.EXTRA_ARGS)
    - --dockerfile=$(params.DOCKERFILE)
    - --context=$(workspaces.source.path)/$(params.CONTEXT)  # The user does not need to care the workspace and the source.
    - --destination=$(params.IMAGE)
    - --digest-file=$(results.IMAGE_DIGEST.path)
    # kaniko assumes it is running as root, which means this example fails on platforms
    # that default to run containers as random uid (like OpenShift). Adding this securityContext
    # makes it explicit that it needs to run as root.
    securityContext:
      runAsUser: 0
  - name: write-digest
    image: bash
    script: |
      set -e
      echo $(params.IMAGE) | tee $(results.IMAGE_URL.path)
      cat "$(results.IMAGE_DIGEST.path)"
    securityContext:
      runAsUser: 0
```

If I change `cm chains-config -n openshift-pipelines` to be:
```
data:
  artifacts.oci.format: simplesigning
  artifacts.oci.storage: oci
  artifacts.taskrun.format: slsa/v1
  artifacts.taskrun.storage: oci
  transparency.enabled: "false"
```

(and then `oc delete po -n openshift-pipelines -l app=tekton-chains-controller` to restart to ensure it's picked up) and then rerun the pipelineRun, I get:
```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: kaniko-chains-pipelinerun-
  annotations:
    chains.tekton.dev/cert-pipelinerun-9fe0312f-c7d4-4004-9e39-3fdfd1dc2b12: ''
    chains.tekton.dev/chain-pipelinerun-9fe0312f-c7d4-4004-9e39-3fdfd1dc2b12: ''
    chains.tekton.dev/payload-pipelinerun-9fe0312f-c7d4-4004-9e39-3fdfd1dc2b12: <redacted>
    chains.tekton.dev/signature-pipelinerun-9fe0312f-c7d4-4004-9e39-3fdfd1dc2b12: <redacted>
    chains.tekton.dev/signed: 'true'
  name: kaniko-chains-pipelinerun-lng9p
```

And in image registry:
![image](https://github.com/tektoncd/chains/assets/33348891/8eca179e-c6f0-4eac-881e-f319201c89d0)

When I `cosign download attestation <registry>/kaniko-chains@sha256... | jq -r .payload | base64 -d | jq | head -20` I get:
```
{
  "_type": "https://in-toto.io/Statement/v0.1",
  "predicateType": "https://slsa.dev/provenance/v0.2",
  "subject": [
    {
      "name": "<redcated>/kaniko-chains",
      "digest": {
        "sha256": "39c67a7db26f9b445ab4886b5da3398d82b4deb0510f094ead6138be964f73e5"
      }
    }
  ],
  "predicate": {
    "builder": {
      "id": "https://tekton.dev/chains/v2"
    },
    "buildType": "tekton.dev/v1beta1/TaskRun",
    "invocation": {
      "configSource": {},
      "parameters": {
        "BUILDER_IMAGE": "gcr.io/kaniko-project/executor:v1.17.0",
```

If I set chains-config to be:
```
oc get cm chains-config -n openshift-pipelines -oyaml | head -10
apiVersion: v1
data:
  artifacts.oci.format: simplesigning
  artifacts.oci.storage: oci
  artifacts.pipelinerun.format: slsa/v1
  artifacts.pipelinerun.storage: tekton
  transparency.enabled: "false"
```

And rerun the pipeline, I get:
```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: kaniko-chains-pipelinerun-
  annotations:
    chains.tekton.dev/cert-pipelinerun-a7e49b33-d536-4f8a-8270-fd50b4cefec2: ''
    chains.tekton.dev/chain-pipelinerun-a7e49b33-d536-4f8a-8270-fd50b4cefec2: ''
    chains.tekton.dev/payload-pipelinerun-a7e49b33-d536-4f8a-8270-fd50b4cefec2: <redacted>
    chains.tekton.dev/signature-pipelinerun-a7e49b33-d536-4f8a-8270-fd50b4cefec2: <redacted>
    chains.tekton.dev/signed: 'true'
  name: kaniko-chains-pipelinerun-5xfsx
```

I can then inspect the payload (with `echo "<payload>"  | base64 -d | jq | head -20`):
```
{
  "_type": "https://in-toto.io/Statement/v0.1",
  "predicateType": "https://slsa.dev/provenance/v0.2",
  "subject": null,
  "predicate": {
    "builder": {
      "id": "https://tekton.dev/chains/v2"
    },
    "buildType": "tekton.dev/v1beta1/PipelineRun",
    "invocation": {
      "configSource": {},
      "parameters": {},
      "environment": {
        "labels": {
          "tekton.dev/pipeline": "simple-kaniko-chains-two-tasks"
        }
      }
    },
    "buildConfig": {
      "tasks": [
``` 

Thanks in advance for any assistance you can provide.
