### ISSUE TITLE
Chains should  expose some more detailed metrics

### ISSUE THREAD

**Issue by jhutar** [tektoncd/chains#1028]
### Feature request

Hello and thank you for Chains development! It would be great if Chains would expose some more detailed metrics besides Knative controller default metrics. Maybe something like "how many artefacts are there still to be processed".

### Use case

I'm trying to measure performance of Chains. Mine approach is to generate as many sign-able artefacts as possible and measure difference between when pod that created artefacts finished and when `"chains.tekton.dev/signed": "true"` annotation appeared.

This is hard to do, because TaskRun yaml does not seem to contain any indication of when the annotation was added, so I have to iterate frequently to get that number.

If there is a metric that could be used to observe the count of remaining images to sign, that would be great.

**Comment by lcarva** [comment]
@jhutar, the immediate alternative that I can think of is through some clever parsing of the controller logs.

Adding the suggested metric seems reasonable to me. I just have no idea how to do so.

@wlynch, @chitrangpatel, are you guys aware of any existing mechanism that could help @jhutar?

**Comment by chitrangpatel** [comment]
Could we add another annotation `"chains.tekton.dev/signedAt": "YYYY-mm-dd HH:MM:SS"`?

Another possible way: 

The Taskrun status also has the following fields:
```
status:
  completionTime: "2024-01-08T19:16:46Z"
  conditions:
  - lastTransitionTime: "2024-01-08T19:16:46Z"
    message: All Steps have completed executing
    reason: Succeeded
    status: "True"
    type: Succeeded
  startTime: "2024-01-08T19:16:37Z"
```
I'm not sure if Chains could update the `completionTime` (or add field to the status) to when it signs the artifacts of that Task?
