### ISSUE TITLE
Parse Type-hinted StepResults for the Provenance

### ISSUE THREAD

**Issue by chitrangpatel** [tektoncd/chains#1065]
### Feature request

Parse type-hinted `StepResults` and surface them appropriately in the provenance
### Use case

StepActions were released in `Tekton Pipelines v0.54.0`. As a part of that, we introduced `StepResults`. `StepResults` are not automatically surfaced to TaskResults. Users explicitly need to fetch them like they do for `PipelineResults` from `TaskResults`. As a result, if a type-hinted `StepResult` is not explicitly surfaced by the user then it will go unnoticed by Chains and thus not be surfaced as a `ResolvedDependency/Material`, `Subject` or `Byproduct`. 

The solution is simple. The formatter just needs to additionally look into the `StepState` for `StepResults`.

## Proposal
Add an extra key `isBuildArtifact` with a boolean value defaulted to `false` to the Type-hinted Object StepResults. When Chains parses the step results, it can look for that field and insert the output artifact into `subject` or `byProducts`. In the new Artifacts Struct defined in https://github.com/tektoncd/community/blob/main/teps/0147-tekton-artifacts-phase1.md, we can add a similar field to `outputs`.

### Pros
* Chains gets accurate intention about what to do with the output artifact.
* The `StepAction/Task` can actually ask the intent to the `Pipeline/TaskRun` via params. 
  * That way, since it is the `Pipeline` that really understands the complete picture, it can indicate the nature of the artifact that the underlying `StepAction/Task` was used to fetch (i.e. `subject` or a `byProduct`).

#### Example
```yaml
apiVersion: tekton.dev/v1alpha1
kind: StepAction
metadata:
  name: gcs-upload
spec:
  image: gcs
  params:
    - name: isBuildArtifact
      description: Should the file/folder you are uploading be considered as a build artifact (subject) or a byProduct?
      default: "false"
  results:
    - name: upload_ARTIFACT_OUTPUT
      type: object
  script: |
    echo {"uri:" ..., "digest": ..., "isBuildArtifact": "$(params.isBuildArtifact)"} | tee $(step.results.upload_ARTIFACT_OUTPUT.path)
---
apiVersion: tekton.dev/v1
kind: TaskRun
spec:
  params:
    - name: isBuildArtifact
      value: "true"
  taskSpec:
    steps:
      - name: step-producing-artifact
        ref:
          name: gcs-upload
        params:
          - name: isBuildArtifact
            value: $(params.isBuildArtifact)
```

### Behavior amongst Task Results, Pipeline Results and StepResults
Based on extensive discussions in the Tekton Chains WG, we've reached the following conclusion:.

To provide a consistent behavior across TaskResults, PipelineResults and StepResults we propose the following.

For non-object type-hinted results, we assume that they are all `byProducts`. 
For object results, we assume that by default `*ARTIFACT_OUTPUTS` are `byProducts`. If a matching key `isBuildArtifact` is found and is set to `true` then Chains considers it as a `subject`.

**Note** that this currently not the behavior for `Task/Pipeline Results` (they are `subjects` by default). This behaviour will be made consistent with `StepResults` so that across the board, users can expect to do the same thing. i.e. declare something as a `build Artifact` to treat it as a `subject`. 
To not break the users immediately, we, propose gating this behind `slsa/v2alpha4` so that users currently using `slsa/v2alpha2,3` do not experience this change. However, once we mature to `slsa/v2beta1`, we will deprecate older alpha versions and this (i.e. `*ARTIFACT_OUTPUTS` are `byProducts` by default and that users have to specifically declare it as a `subject`) will be the expected behavior.
