### ISSUE TITLE
Unable to upload provenance data to OCI while using in-toto format

### ISSUE THREAD

**Issue by yfolias** [tektoncd/chains#253]
# Expected Behavior
The expected behaviour would include uploading in-toto provenance data to an OCI registry.

# Actual Behavior
While using in-toto provenance and OCI storage due to erroneous usage of the digest twice resulting in the following error.  
```
a digest must contain exactly one '@' separator (e.g. registry/repository@digest) saw: pkg:docker/something/something@sha256:f893fccbb72584ab6eb5afd026c5dd55795d3d68c5557cf7587aa2fe9c1e422a@sha256:f893fccbb72584ab6eb5afd026c5dd55795d3d68c5557cf7587aa2fe9c1e422a
```
This issue doesn't exist for Tekton provenance.

# Steps to Reproduce the Problem

1. Edit chains-config and specify `artifacts.taskrun.format: in-toto`
2. Configure chains to use an OCI registry
```
data:
  artifacts.oci.format: simplesigning
  artifacts.oci.signer: x509
  artifacts.oci.storage: oci
  artifacts.taskrun.format: in-toto
  artifacts.taskrun.signer: x509
  artifacts.taskrun.storage: oci
  storage.oci.repository: [target repository]
```
3. Run pipeline and retrieve the tekton-chains-controller logs
`kubectl logs -l app=tekton-chains-controller -n tekton-chains`

# Additional Info

- Kubernetes version: `v1.22.2`
- Tekton Pipeline version: `v0.28.1`
- Tekton chains version: `v0.5.0`
