### ISSUE TITLE
Add a `chains-info` ConfigMap to expose Chains' version

### ISSUE THREAD

**Issue by concaf** [tektoncd/chains#336]
Other Tekton components like Pipeline and Triggers expose a `<component>-info` ConfigMap which can be queried by external tools such as CLI, primarily to query for the component's version.

See https://github.com/tektoncd/pipeline/blob/e0e994e3def8efe51d921b1cd579c8b9cde32ddd/config/config-info.yaml#L15-L29 and https://github.com/tektoncd/triggers/blob/7fbff3b122fcb77d44e1b39bb45c8a935e61f5ed/config/config-info.yaml#L15-L29

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: pipelines-info
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
data:
  # Contains pipelines version which can be queried by external
  # tools such as CLI. Elevated permissions are already given to
  # this ConfigMap such that even if we don't have access to
  # other resources in the namespace we still can have access to
  # this ConfigMap.
  version: "devel"
```
