### ISSUE TITLE
Question: Use of anyuid for tekton-chains-controller

### ISSUE THREAD

**Issue by mtcolman** [tektoncd/chains#366]
Hi, from looking at the [Installation on OpenShift](https://github.com/tektoncd/chains#installation-on-openshift) section of the README it states "To install Tekton Chains on OpenShift, you must first apply the `anyuid` security context constraint to the `tekton-chains-controller service account`" can you please confirm why?

From looking at the [deployment manifest](https://github.com/tektoncd/chains/blob/main/config/100-deployment.yaml) I can see the security context being as follows:
```
    spec:
      serviceAccountName: tekton-chains-controller
      containers:
      - name: tekton-chains-controller
      ...
      ...
        securityContext:
          allowPrivilegeEscalation: false
          # User 65532 is the distroless nonroot user ID
          runAsUser: 65532
          runAsGroup: 65532
```

If the reason is due to `runAsUser: 65532` and `runAsGroup: 65532` then this can be achieved with the SCC `nonroot`, which doesn't permit the use of `root` user (UID=0) which the `anyuid` SCC does.
