### ISSUE TITLE
Add maven package support using simple type hinting in intoto provenance

### ISSUE THREAD

**Issue by ywluogg** [tektoncd/chains#460]
### Feature request

Add maven package support using simple type hinting in intoto.
Currently we support git source and OCI images. Supporting maven packages in image in simple type hinting gives extra support of such type of artifact and let users to use Chains before TEP 0075, 0076 and 0109 can be released.

### Use case
We will have:
``` yaml
      results:
        - name: mvn1_pkg_INTOTO_TARGET_NAME
           value: maven-test-0.0.1.jar
        - name: mvn1_pkg_INTOTO_TARGET_DIGEST
           value: sha256@abc
        - name: mvn1_pom_INTOTO_TARGET_NAME
           value: maven-test-0.0.1.pom
        - name: mvn1_pom_INTOTO_TARGET_DIGEST
           value: sha256@def
        - name: mvn1_src_INTOTO_TARGET_NAME
           value: maven-test-0.0.1-sources.jar
        - name: mvn1_src_INTOTO_TARGET_DIGEST
           value: sha256@xyz
```

From this, we will generate a subject in intoto provenence:
```
{"name": "maven-test-0.0.1.jar", "digest": {"sha256": "abc"}}
{"name": "maven-test-0.0.1.pom", "digest": {"sha256": "def"}}
{"name": "maven-test-0.0.1-sources.jar", "digest": {"sha256": "xyz"}}
```
