### ISSUE TITLE
missing document key (code=InvalidArgument)

### ISSUE THREAD

**Issue by michaelsatish** [tektoncd/chains#556]
I am not sure this is a bug, thus an unstructured issue. I have been trying to store the OCI signatures in AWS DynamoDB and running into the below error. Any help will be much appreciated. 

**Config**

```yaml
configMapGenerator:
  - name: chains-config
    namespace: tekton-chains
    behavior: merge
    literals:
      - artifacts.oci.storage=docdb
      - artifacts.oci.signer=x509
      - storage.docdb.url=dynamodb://tekton-chains-oci-storage?partition_key=key

```

```json
{"level":"error","ts":"2022-09-15T00:32:37.745Z","logger":"watcher","caller":"chains/signing.go:204","msg":"missing document key (code=InvalidArgument)"
```

I think the URL is correct, as the below code works.

```go
package main

import (
	"context"
	"log"

	"gocloud.dev/docstore"
	_ "gocloud.dev/docstore/awsdynamodb"
)

func main() {
	ctx := context.TODO()
	coll, err := docstore.OpenCollection(ctx, "dynamodb://tekton-chains-oci-storage?partition_key=key")
	if err != nil {
		log.Fatal(err)
	}
	defer coll.Close()
	coll.Put(ctx, map[string]interface{}{"key": "bar"})
}
```

Thank you
