### ISSUE TITLE
`ARTIFACT_INPUTS` type hinting cannot work with digest "sha1:xxxx"

### ISSUE THREAD

**Issue by chuangw6** [tektoncd/chains#636]
# Expected Behavior

`ARTIFACT_INPUTS` type hinting works for git uri and digest for which algorithm is "sha1".

# Actual Behavior

`ARTIFACT_INPUTS` type hinting cannot recognize git uri and digest because algorithm is not "sha256" and the sha1 hex value cannot pass the validation as well.

# Background
We recently introduced new type hinting approach using structure type result . For example, to identify the source repo information i.e. uri and digest that will be recorded in `predicate.materials` section, Chains looks for an object result that has suffix `ARTIFACT_INPUTS` with two keys `uri` and `digest`. 

For git sources, the digest algorithm will be `sha1`. That implies the value for the `digest` key of `ARTIFACT_INPUTS` has to be "sha1:xxxxx". But Chains has digest validation and the validation is mainly for sha256 digest i.e. length, and the algorithm has to be "sha256". "sha1" will not be recognized.

# Steps to Reproduce the Problem

1. enable alpha feature flag in pipeline to use object result
2. generate a key pair https://github.com/tektoncd/chains/blob/main/docs/signing.md#generate-cosign-keypair
3. apply chains configmap
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: chains-config
  namespace: tekton-chains
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-chains
data:
  artifacts.taskrun.storage: ""
  artifacts.oci.storage: ""
  artifacts.pipelinerun.format: in-toto
  artifacts.pipelinerun.storage: tekton
```
3. run the following yaml
```yaml
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-pipeline
spec:
  workspaces:
    - name: shared
  params:
    - name: git-repo
      description: The source repo to clone.
    - name: git-revision
      description: The revision of the source repo.
  results:
    - name: ARTIFACT_INPUTS
      type: object
      value:
        uri: $(tasks.clone-source.results.url)
        digest: sha1:$(tasks.clone-source.results.commit)
  tasks:
    - name: clone-source
      taskRef:
        resolver: bundles
        params:
          - name: bundle
            value: gcr.io/tekton-releases/catalog/upstream/git-clone:0.7
          - name: name
            value: git-clone
          - name: kind
            value: task
      params:
        - name: url
          value: $(params.git-repo)
        - name: revision
          value: $(params.git-revision)
      workspaces:
        - name: output
          workspace: shared
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: clone-pipelinerun
spec:
  params:
    - name: git-repo
      value: https://github.com/chuangw6/tekton-test
    - name: git-revision
      value: main
  pipelineRef:
    name: clone-pipeline
  workspaces:
    - name: shared
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 500Mi
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.7-gke.900", GitCommit:"e35c4457f66187eff006dda6d2c0fe12144ef2ec", GitTreeState:"clean", BuildDate:"2022-10-26T09:25:34Z", GoVersion:"go1.18.7b7", Compiler:"gc", Platform:"linux/amd64"}
  ```

- Tekton Pipeline version:

v0.42
