### ISSUE TITLE
Fix Intoto signature storage in Grafeas occurrence

### ISSUE THREAD

**Issue by chuangw6** [tektoncd/chains#743]
The signature for intoto attestation generated by Chains is in the format of DSSE envelope that contains 3 things: the payload, payloadtype and PAE signature. 

```yaml
{
  "payload": "<Base64(SERIALIZED_BODY)>",
  "payloadType": "<PAYLOAD_TYPE>",
  "signatures": [{
    "keyid": "<KEYID>",
    "sig": "<Base64(PAE SIGNATURE)>"
  }]
}
```

When storing into grafeas BUILD occurrence, we need to unpack the chains-generated signature and convert the 3 things into the corresponding fields in the envelope of the grafeas BUILD occurrence. 

However, current implementation is that the signature produced by Chains is stored directly into the signature of the envelope, which is incorrect.

Related to https://github.com/tektoncd/chains/issues/707
