### ISSUE TITLE
Add resolved top-level build config yaml to external parameters

### ISSUE THREAD

**Issue by chitrangpatel** [tektoncd/chains#846]
In https://docs.google.com/document/d/1ewqtPXyg_y3MmU6Tc6l1X8nfzjt0AJHlP6VOnFsGNpQ/edit#heading=h.8hw7rf805u8r, we decided the add the complete `runSpec` to `externalParameters` and the resolved top-level task/pipeline yaml to resolved dependencies. This has caused some friction in alignment between the Slsa specification, builders and verifiers.

According to the [SLSA spec](https://slsa.dev/provenance/v1#provenance), the external parameters should capture the inputs to the build interface. In the case where the build config is located remotely (e.g. in version control), one of the key ingredients that **must be validated** is the repo from where the build config was fetched. This information is available in the `runSpec` under `pipelineRef` or the `taskRef` however, that syntax is very specific to Tekton which makes it very challenging for generic verifiers (that validate provenances from several CI/CD systems) to identify without making the verification policy understand the Tekton API. To make matters worse, the repo uri is not necessarily embedded in the [resolver parameters](https://github.com/tektoncd/pipeline/blob/main/pkg/resolution/resolver/git/params.go). This means that depending on the parameters, verifiers need to add logic to extract the URI for verification. 

In Tekton Chains, we have this information completely resolved and accessible. However, we add this to the resolved dependencies section of the provenance. 

Here, we also propose adding this resolved URI to externalParameters to make it easy for generic verifies (like binary Authorization) to access a field that can be easily verified.

**Note** that this will also make it synchronous with the suggested [migration path from SLSA v0.2 to v1.0](https://slsa.dev/provenance/v1#migrating-from-02) where it says that the externalParameters should also contain the `old invocation.ConfigSource`. 

cc @chuangw6, @bobcatfish, @MarkLodato

**Comment by chuangw6** [comment]
Thanks @chitrangpatel !
The idea SGTM. Can you please be explicit about the extra field we want to introduce to the externalParameters? Is it just a single uri field, or is it an object containing key value pairs such as uri, digest and entryppoint? Also what names should we use for those fields?

**Comment by chitrangpatel** [comment]
I was thinking of this:
```yaml
buildConfigSource:
  ref: either git reference (i.e. commit sha - sha1:xxxx) or image digest (e.g. sha256:91fb5e20325059e8feb48c966a83d616596054c5edf811b5bc673683e6ecabb6)
  repository: either git repository uri or image repository uri
  path: either path in the git repo or the resource name in the image bundle.
```
